import pytest
from fastapi.testclient import TestClient
from pytest_mock import MockerFixture

# Assuming client fixture is available from test_app.py and handles app setup
# from ..app import app as fastapi_app # If client fixture is not auto-discovered or app is needed directly

from models.api_models import DeviceListItem, DeviceResponse, DeviceCreate, DeviceUpdate

# Sample data consistent with models/api_models.py
SAMPLE_DEVICE_ID_1 = "test-uuid-1"
SAMPLE_DEVEUI_1 = "0011223344556677"
SAMPLE_DEVEUI_2 = "AABBCCDDEEFF0011"

sample_device_list_item_1 = DeviceListItem(
    id=SAMPLE_DEVICE_ID_1,
    devEui=SAMPLE_DEVEUI_1, # Added from DeviceBase
    trashbin_id="tb-uuid-1",   # Added from DeviceBase (example)
    last_seen="2023-01-01T12:00:00Z",
    battery_level=80,
    latest_data_id=1
)

sample_device_response_1 = DeviceResponse(
    id=SAMPLE_DEVICE_ID_1,
    devEui=SAMPLE_DEVEUI_1,
    trashbin_id="tb-uuid-1", # Added from DeviceBase (example)
    deviceProfileName="test-profile",
    battery_level=80,
    last_seen="2023-01-01T12:00:00Z",
    latest_data_id=1
)

# Tests for GET /device/
def test_get_device_list_success(client: TestClient, mocker: MockerFixture):
    """Test successful retrieval of device list."""
    mock_get_list = mocker.patch('api.device_service.get_list', return_value=[sample_device_list_item_1])
    
    response = client.get("/api/v0/device/")
    
    assert response.status_code == 200
    assert response.json() == [sample_device_list_item_1.model_dump()]
    mock_get_list.assert_called_once_with(mocker.ANY) # mocker.ANY for db dependency

def test_get_device_list_empty(client: TestClient, mocker: MockerFixture):
    """Test retrieval of an empty device list."""
    mock_get_list = mocker.patch('api.device_service.get_list', return_value=[])
    
    response = client.get("/api/v0/device/")
    
    assert response.status_code == 200
    assert response.json() == []
    mock_get_list.assert_called_once_with(mocker.ANY)

# Tests for GET /device/{device_id}
def test_get_device_details_success(client: TestClient, mocker: MockerFixture):
    """Test successful retrieval of specific device details."""
    mock_get_device = mocker.patch('api.device_service.get_device', return_value=sample_device_response_1)
    
    response = client.get(f"/api/v0/device/{SAMPLE_DEVICE_ID_1}")
    
    assert response.status_code == 200
    assert response.json() == sample_device_response_1.model_dump()
    mock_get_device.assert_called_once_with(mocker.ANY, SAMPLE_DEVICE_ID_1)

def test_get_device_details_not_found(client: TestClient, mocker: MockerFixture):
    """Test retrieval of a non-existent device."""
    device_id = "non-existent-uuid"
    mock_get_device = mocker.patch('api.device_service.get_device', return_value=None)
    
    response = client.get(f"/api/v0/device/{device_id}")
    
    assert response.status_code == 404
    assert response.json() == {"detail": f"Device with ID {device_id} not found"}
    mock_get_device.assert_called_once_with(mocker.ANY, device_id)

# Tests for POST /device/
def test_create_device_success(client: TestClient, mocker: MockerFixture):
    """Test successful creation of a new device."""
    create_payload = DeviceCreate(
        devEui=SAMPLE_DEVEUI_2,
        trashbin_id="new-tb-uuid"
    )
    created_device_response = DeviceResponse(
        id="new-generated-uuid", # ID would be generated by the service
        devEui=create_payload.devEui,
        trashbin_id=create_payload.trashbin_id,
        deviceProfileName="default-profile", # Example default
        battery_level=None,
        last_seen=None,
        latest_data_id=None
    )
    mock_create_service = mocker.patch('api.device_service.create', return_value=created_device_response)
    
    response = client.post("/api/v0/device/", json=create_payload.model_dump())
    
    assert response.status_code == 201
    assert response.json() == created_device_response.model_dump()
    mock_create_service.assert_called_once_with(mocker.ANY, create_payload)

def test_create_device_service_returns_none(client: TestClient, mocker: MockerFixture):
    """Test device creation failure when service returns None."""
    create_payload = DeviceCreate(devEui=SAMPLE_DEVEUI_2) # Adjusted to valid DeviceCreate
    mock_create_service = mocker.patch('api.device_service.create', return_value=None)
    
    response = client.post("/api/v0/device/", json=create_payload.model_dump())
    
    assert response.status_code == 500
    assert response.json() == {"detail": "Failed to create device: 500: Failed to create device"}
    mock_create_service.assert_called_once_with(mocker.ANY, create_payload)

def test_create_device_service_raises_exception(client: TestClient, mocker: MockerFixture):
    """
    Test device creation failure when service raises an exception.
    
    This test verifies that the API properly handles and reports exceptions
    that occur during device creation, returning appropriate status codes
    and error messages to the client.
    """
    create_payload = DeviceCreate(devEui=SAMPLE_DEVEUI_2) # Adjusted to valid DeviceCreate
    error_message = "Database connection error"
    mock_create_service = mocker.patch('api.device_service.create', side_effect=Exception(error_message))
    
    response = client.post("/api/v0/device/", json=create_payload.model_dump())
    
    assert response.status_code == 500
    assert response.json() == {"detail": f"Failed to create device: {error_message}"}
    mock_create_service.assert_called_once_with(mocker.ANY, create_payload)

# Tests for PUT /device/{device_id}
def test_update_device_success(client: TestClient, mocker: MockerFixture):
    """Test successful update of an existing device."""
    # DeviceUpdate requires 'id' as it inherits from DeviceBase.
    # devEui and trashbin_id are also part of DeviceBase but optional.
    update_payload = DeviceUpdate(
        id=SAMPLE_DEVICE_ID_1, # Required by DeviceUpdate model (via DeviceBase)
        devEui=SAMPLE_DEVEUI_1, # Carry over from original or set to new
        deviceProfileName="updated-profile", 
        battery_level=90
    )
    # Create an updated response based on the original sample_device_response_1
    # Ensure all fields for DeviceResponse are present
    updated_device_response = sample_device_response_1.model_copy(
        update={
            "deviceProfileName": update_payload.deviceProfileName, 
            "battery_level": update_payload.battery_level,
            # Ensure other fields of DeviceResponse are correctly represented if they change
            # For this test, we assume only profile name and battery level are changed by the payload
        }
    )
    # If devEui can be updated, it should be reflected in updated_device_response too.
    # For now, assuming devEui in payload is for matching or can be updated.
    if update_payload.devEui is not None:
        updated_device_response.devEui = update_payload.devEui


    mock_update_service = mocker.patch('api.device_service.update', return_value=updated_device_response)

    # Pass exclude_unset=True if you only want to send fields that are explicitly set in update_payload
    # However, DeviceUpdate requires 'id', so it must be present.
    response = client.put(f"/api/v0/device/{SAMPLE_DEVICE_ID_1}", json=update_payload.model_dump(exclude_none=True)) # exclude_none might be better

    assert response.status_code == 200
    assert response.json() == updated_device_response.model_dump()
    # The service layer receives the device_id from the path and the payload.
    # The Pydantic model `device_update` will be `update_payload`.
    mock_update_service.assert_called_once_with(mocker.ANY, SAMPLE_DEVICE_ID_1, update_payload)

def test_update_device_not_found(client: TestClient, mocker: MockerFixture):
    """Test updating a non-existent device."""
    device_id = "non-existent-uuid"
    # Payload must be valid DeviceUpdate, including required 'id'
    update_payload = DeviceUpdate(id=device_id, deviceProfileName="Updated Profile Name")
    mock_update_service = mocker.patch('api.device_service.update', return_value=None)

    response = client.put(f"/api/v0/device/{device_id}", json=update_payload.model_dump(exclude_none=True))

    assert response.status_code == 404
    assert response.json() == {"detail": f"Device with ID {device_id} not found or update failed"}
    mock_update_service.assert_called_once_with(mocker.ANY, device_id, update_payload)

# Tests for DELETE /device/{device_id}
def test_delete_device_success(client: TestClient, mocker: MockerFixture):
    """Test successful deletion of a device."""
    # The service's delete function might return a boolean or specific object.
    # The router expects a non-None result for success.
    mock_delete_service = mocker.patch('api.device_service.delete', return_value={"status": "deleted"}) 

    response = client.delete(f"/api/v0/device/{SAMPLE_DEVICE_ID_1}")

    assert response.status_code == 200
    assert response.json() == {"message": "Device deleted successfully", "device_id": SAMPLE_DEVICE_ID_1}
    mock_delete_service.assert_called_once_with(mocker.ANY, SAMPLE_DEVICE_ID_1)

def test_delete_device_not_found(client: TestClient, mocker: MockerFixture):
    """Test deleting a non-existent device."""
    device_id = "non-existent-uuid"
    mock_delete_service = mocker.patch('api.device_service.delete', return_value=None)

    response = client.delete(f"/api/v0/device/{device_id}")

    assert response.status_code == 404
    assert response.json() == {"detail": f"Device with ID {device_id} not found"}
    mock_delete_service.assert_called_once_with(mocker.ANY, device_id)
