detectors:
  - name: wifi-password
    keywords:
      - wpa_passphrase
      - wpa_psk
      - psk=
      - wlan
      - wlankey
      - wireless_key
      - wlan_key
      - wlan_passwort
      - wlan_pass
    regex:
      wifi_key: '(?i)psk[=\s:]+["\047]?([a-zA-Z0-9]{8,63})["\047]?'
      wifi_pass: '(?i)[\s"-]*[Pp]asswort[\s:]+([a-zA-Z0-9]{8,})'
