"""Add latest_fill_level to trashbin table

Revision ID: 16e0eb5c67a3
Revises: 9d83aac8e7c6
Create Date: 2025-06-09 14:18:14.230475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16e0eb5c67a3'
down_revision: Union[str, None] = '9d83aac8e7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trashbin', sa.Column('latest_fill_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trashbin', 'latest_fill_level')
    # ### end Alembic commands ###
