"""Trashbin / DataLog adjustments

Revision ID: 67583f41494c
Revises: 946dd07f59a5
Create Date: 2025-05-13 10:38:10.780002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67583f41494c'
down_revision: Union[str, None] = '946dd07f59a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datalog', sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trashbin', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('trashbin', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trashbin', sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trashbin', 'status')
    op.drop_column('datalog', 'payload')
    # ### end Alembic commands ###
