"""trashbin update

Revision ID: 946dd07f59a5
Revises: ee83206bb79f
Create Date: 2025-05-12 09:45:31.010087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '946dd07f59a5'
down_revision: Union[str, None] = 'ee83206bb79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datalog', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('datalog_trashbin_id_fkey', 'datalog', type_='foreignkey')
    op.add_column('device', sa.Column('trashbin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('device', 'location')
    op.drop_column('device', 'status')
    op.drop_column('device', 'name')
    op.drop_column('device', 'firmware_version')
    op.alter_column('trashbin', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('trashbin_device_id_fkey', 'trashbin', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('trashbin_device_id_fkey', 'trashbin', 'device', ['device_id'], ['id'])
    op.alter_column('trashbin', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('device', sa.Column('firmware_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('device', 'trashbin_id')
    op.create_foreign_key('datalog_trashbin_id_fkey', 'datalog', 'trashbin', ['trashbin_id'], ['id'])
    op.alter_column('datalog', 'distance',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
