"""trashbin optional payload

Revision ID: 9d83aac8e7c6
Revises: 67583f41494c
Create Date: 2025-05-16 12:45:21.204656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d83aac8e7c6'
down_revision: Union[str, None] = '67583f41494c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datalog', 'payload',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datalog', 'payload',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
