"""Remove chirpstack stuff for now

Revision ID: b49766ff6503
Revises: eb73354b5a35
Create Date: 2025-07-03 08:34:59.116781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b49766ff6503'
down_revision: Union[str, None] = 'eb73354b5a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chirpstackcreds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chirpstackcreds',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chirpstackcreds_pkey')
    )
    # ### end Alembic commands ###
