services:
  chirpstack:
    image: chirpstack/chirpstack:4
    container_name: chirpstack
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      - chirpstack-postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=chirpstack-mosquitto
      - REDIS_HOST=chirpstack-redis
      - POSTGRESQL_HOST=chirpstack-postgres
#    ports:
#      - "8080:8080"
    networks:
      - traefik_net
      - citbin_net
    labels:
      - "io.portainer.accesscontrol.teams=azubis"
      - "traefik.enable=true"
      - "traefik.http.routers.chirpstack-http.rule=Host(`chirpstack.sybit.education`)"
      - "traefik.http.routers.chirpstack-http.entrypoints=web"
      - "traefik.http.routers.chirpstack.rule=Host(`chirpstack.sybit.education`)"
      - "traefik.http.routers.chirpstack.entrypoints=web-secure"
      - "traefik.http.routers.chirpstack.tls=true"
      - "traefik.http.routers.chirpstack.middlewares=secHeaders@file"
      - "traefik.http.services.chirpstack.loadbalancer.server.port=8080"
#      - "traefik.http.routers.chirpstack.middlewares=myheader@docker"
#      - "traefik.http.middlewares.myheader.headers.customFrameOptionsValue=ALLOW-FROM https://chirpstack.sybit.education"
#      - "traefik.http.middlewares.myheader.headers.contentSecurityPolicy=frame-ancestors https://chirpstack.sybit.education"


  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    container_name: chirpstack-gateway-bridge
    restart: unless-stopped
    ports:
      - "1700:1700/udp"
    networks:
      - citbin_net
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
    depends_on:
      - mosquitto
    labels:
      - "io.portainer.accesscontrol.teams=azubis"

  chirpstack-gateway-bridge-basicstation:
    image: chirpstack/chirpstack-gateway-bridge:4
    container_name: chirpstack-gateway-basicstation
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
    ports:
      - "3001:3001"
    networks:
      - citbin_net
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto
    labels:
      - "io.portainer.accesscontrol.teams=azubis"

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    container_name: chirpstack-rest-api
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
#    ports:
#      - "8090:8090"
    depends_on:
      - chirpstack
    networks:
      - traefik_net
      - citbin_net
    labels:
      - "io.portainer.accesscontrol.teams=azubis"
      - "traefik.enable=true"
      - "traefik.http.routers.chirpstack-api-http.rule=Host(`chirpstack-api.sybit.education`)"
      - "traefik.http.routers.chirpstack-api-http.entrypoints=web"
      - "traefik.http.routers.chirpstack-api.rule=Host(`chirpstack-api.sybit.education`)"
      - "traefik.http.routers.chirpstack-api.entrypoints=web-secure"
      - "traefik.http.routers.chirpstack-api.tls=true"
      - "traefik.http.routers.chirpstack-api.middlewares=secHeaders@file"
      - "traefik.http.services.chirpstack-api.loadbalancer.server.port=8090"
#      - "traefik.http.routers.chirpstack-api.middlewares=myheader@docker"
#      - "traefik.http.middlewares.myheader.headers.customFrameOptionsValue=ALLOW-FROM https://chirpstack-api.sybit.education"
#      - "traefik.http.middlewares.myheader.headers.contentSecurityPolicy=frame-ancestors https://chirpstack-api.sybit.education"

  chirpstack-postgres:
    image: postgres:14-alpine
    container_name: chirpstack-postgres
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack
    networks:
      - citbin_net
    labels:
      - "io.portainer.accesscontrol.teams=azubis"

  redis:
    image: redis:7-alpine
    container_name: chirpstack-redis
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - ./redisdata:/data
    networks:
      - citbin_net
    labels:
      - "io.portainer.accesscontrol.teams=azubis"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./configuration/mosquitto/config/:/mosquitto/config/
    networks:
      - traefik_net    
      - citbin_net
    labels:
      - "io.portainer.accesscontrol.teams=azubis"

  citbin-postgres:
    image: postgres:16-alpine
    container_name: citbin-postgres
    restart: unless-stopped
    volumes:
      - ./citbin-postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=citbin
      - POSTGRES_PASSWORD=citbin2025!
      - POSTGRES_DB=citbin
    networks:
      - citbin_net
    labels:
      - "io.portainer.accesscontrol.teams=azubis"
      
  #citbin-simulator:
  #  image: ghcr.io/hgs-itg26/mhgs-software-simulator:latest
  #  container_name: citbin-simulator
  #  depends_on:
  #    - mosquitto
  #  environment:
  #    - DEVICE_ID=eui-7066e1fffe00a9e2
  #    - SLEEP_TIME=120
  #    - BACKEND_API_URL=citbin-backend:8000
  #    - ./configuration/mosquitto/config/:/mosquitto/config/
  #  networks:
  #    - citbin_net      
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"    
  #    - "io.portainer.accesscontrol.teams=azubis"
                    
  citbin-backend:
    image: ghcr.io/hgs-itg26/mhgs-software-backend:latest
    container_name: citbin-backend
    restart: unless-stopped
    depends_on:
      - mosquitto
      - citbin-postgres    
    networks:
      - traefik_net
      - citbin_net
    environment:
      - POSTGRES_HOST=citbin-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=citbin
      - POSTGRES_PASSWORD=citbin2025!
      - POSTGRES_DB=citbin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"    
      - "io.portainer.accesscontrol.teams=azubis"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"      
      - "traefik.http.routers.citbin-backend-http.rule=Host(`citbin-backend.sybit.education`)"
      - "traefik.http.routers.citbin-backend-http.entrypoints=web"
      - "traefik.http.routers.citbin-backend.rule=Host(`citbin-backend.sybit.education`)"
      - "traefik.http.routers.citbin-backend.entrypoints=web-secure"
      - "traefik.http.routers.citbin-backend.tls=true"
      - "traefik.http.routers.citbin-backend.middlewares=secHeaders@file"
      - "traefik.http.services.citbin-backend.loadbalancer.server.port=8000"
  
  citbin-frontend:
    image: ghcr.io/hgs-itg26/mhgs-software-frontend:latest
    container_name: citbin-frontend
    restart: unless-stopped
    depends_on:
      - citbin-postgres     
    networks:
      - traefik_net
      - citbin_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"    
      - "io.portainer.accesscontrol.teams=azubis"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.citbin-frontend-http.rule=Host(`citbin.sybit.education`)"
      - "traefik.http.routers.citbin-frontend-http.entrypoints=web"
      - "traefik.http.routers.citbin-frontend.rule=Host(`citbin.sybit.education`)"
      - "traefik.http.routers.citbin-frontend.entrypoints=web-secure"
      - "traefik.http.routers.citbin-frontend.tls=true"
      - "traefik.http.routers.citbin-frontend.middlewares=secHeaders@file"
      - "traefik.http.services.citbin-frontend.loadbalancer.server.port=3000"    
    environment:
      - NEXT_PUBLIC_API_URL=https://citbin-backend.sybit.education

#volumes:
#  postgresqldata:
#  redisdata:

networks:
  traefik_net:
    external: true
  citbin_net:
